depth_mapping = {
    # 상의
    "Short_Sleeve_TShirts": ("상의", "티셔츠", "반소매 티셔츠"),
    "Long_Sleeve_TShirts": ("상의", "티셔츠", "긴소매 티셔츠"),
    "Sleeveless_Shirts": ("상의", "티셔츠", "민소매 티셔츠"),
    "Sweatshirts": ("상의", "티셔츠", "맨투맨/스웨트"),
    "Hooded_TShirts": ("상의", "티셔츠", "후드 티셔츠"),
    "Shirts": ("상의", "셔츠", "셔츠"),
    "Blouses": ("상의", "셔츠", "블라우스"),
    "Pique_Collar_Shirts": ("상의", "티셔츠", "피케/카라"),
    "Polos_TShirts": ("상의", "티셔츠", "폴로"),
    "Short_Sleeve_Shirts": ("상의", "셔츠", "반소매 셔츠"),
    "Long_Sleeve_Shirts": ("상의", "셔츠", "긴소매 셔츠"),
    
    # 하의
    "Shorts": ("하의", "팬츠", "숏 팬츠"),
    "Slim_Fit_Pants": ("하의", "팬츠", "슬림 팬츠"),
    "Straight_Pants": ("하의", "팬츠", "스트레이트 팬츠"),
    "Wide_Pants": ("하의", "팬츠", "와이드 팬츠"),
    "Denim_Pants": ("하의", "팬츠", "데님"),
    "Training_Pants": ("하의", "팬츠", "트레이닝"),
    "Leggings": ("하의", "팬츠", "레깅스"),
    "Slacks": ("하의", "팬츠", "슬랙스"),
    "Suit_Pants_Slacks": ("하의", "팬츠", "슬랙스"),
    "Bootcut_Pants": ("하의", "팬츠", "부츠컷"),
    "Other_Pants": ("하의", "팬츠", "기타 하의"),

    # 아우터
    "Windbreakers": ("아우터", "자켓", "바람막이"),
    "Blazers": ("아우터", "자켓", "블레이저"),
    "Shearling_Jackets": ("아우터", "자켓", "무스탕"),
    "Leather_Riders_Jackets": ("아우터", "자켓", "레더/라이더스 자켓"),
    "Jackets": ("아우터", "자켓", "자켓"),
    "Training_Jackets": ("아우터", "자켓", "트레이닝"),
    "Denim_Trucker_Jackets": ("아우터", "자켓", "데님/트러커 자켓"),
    "Fur_Jackets": ("아우터", "플리스", "퍼 자켓"),
    "Nylon_Coach_Jackets": ("아우터", "자켓", "나일론/코치 자켓"),
    "Hooded_ZipUps": ("아우터", "자켓", "후드집업"),
    "Jumpers": ("아우터", "자켓", "점퍼"),
    "Anoraks": ("아우터", "자켓", "아노락 자켓"),
    "Fleece_Jackets": ("아우터", "플리스", "플리스/뽀글이"),
    "Half_Coats": ("아우터", "코트", "하프코트"),
    "Trench_Coats": ("아우터", "코트", "트렌치코트"),
    "Trench_Mac_Coats": ("아우터", "코트", "트렌치코트"),
    "Short_Coats": ("아우터", "코트", "숏코트"),
    "Long_Coats": ("아우터", "코트", "롱코트"),
    "Lightweight_Padding": ("아우터", "패딩", "경량패딩"),
    "Short_Padding": ("아우터", "패딩", "숏패딩"),
    "Long_Padding": ("아우터", "패딩", "롱패딩"),
    "Vests": ("아우터", "플리스", "베스트"),
    "Robes": ("아우터", "기타", "로브"),
    "MA1_Bombers": ("아우터", "자켓", "블루종/MA-1"),
    "Stadium_Jackets": ("아우터", "자켓", "스타디움 자켓"),
    "Military_Jackets": ("아우터", "자켓", "야상"),
    "Other_Outerwear": ("아우터", "기타", "기타 아우터"),

    # 원피스
    "Mini_Dresses": ("하의", "원피스", "미니 원피스"),
    "Midi_Maxi_Dresses": ("하의", "원피스", "미디/맥시 원피스"),
    "Long_Dresses": ("하의", "원피스", "롱 원피스"),
    "Denim_Dresses": ("하의", "원피스", "데님 원피스"),

    # 스커트
    "Mini_Skirts": ("하의", "스커트", "미니 스커트"),
    "Midi_Skirts": ("하의", "스커트", "미디 스커트"),
    "Long_Skirts": ("하의", "스커트", "롱 스커트"),
    "Denim_Skirts": ("하의", "스커트", "데님 스커트"),

    # 니트웨어
    "Crewnecks": ("상의", "니트", "크루넥"),
    "V_Necks": ("상의", "니트", "브이넥"),
    "Cashmere": ("상의", "니트", "캐시미어"),
    "Cardigans": ("상의", "니트", "카디건"),
    "Knit_Vests": ("상의", "니트", "베스트"),
    "Turtlenecks": ("상의", "니트", "터틀넥"),
    "Other_Knitwear": ("상의", "니트", "기타 니트"),
    "Polos_Knit": ("상의", "니트", "폴로"),
    "Hoodies": ("상의", "니트", "후디"),
    "Knit_ZipUps": ("상의", "니트", "집업"),

    # 신발
    "Flats_Loafers": ("신발", "신발", "플랫/로퍼"),
    "Boots": ("신발", "신발", "부츠/워커"),
    "Sandals": ("신발", "신발", "샌들/슬리퍼"),
    "Pumps": ("신발", "신발", "구두/펌프스"),
    "Slippers_Mules": ("신발", "신발", "뮬/블로퍼"),
    "Sneakers": ("신발", "신발", "스니커즈"),
    "Loafers": ("신발", "신발", "로퍼"),
    "Dress_Shoes": ("신발", "신발", "구두"),
}
