redshift:
  outputs:
    dev:
      type: redshift
      host: redshift-cluster-endpoint
      user: your-username
      password: your-password
      port: 5439
      dbname: your-database
      schema: public
      threads: 4
  target: dev
