apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: ${AWS_USER_ARN}
      username: ${AWS_USER_NAME}  # IAM 사용자 이름 (예: my-eks-user)
      groups:
        - system:masters
