apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: pyspark-sleep-job
  namespace: spark
spec:
  type: Python
  mode: cluster
  image: gcr.io/spark-operator/spark-py:v3.1.1
  mainApplicationFile: "local:///mnt/spark_job/spark_sleep.py"  # PVC에 저장된 PySpark 코드 경로
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10s
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20s
  volumes:  # PVC를 Spark Driver 및 Executor에 마운트
    - name: spark-pvc
      persistentVolumeClaim:
        claimName: spark-pvc
  driver:
    cores: 1
    memory: "512Mi"
    volumeMounts:
      - name: spark-pvc
        mountPath: "/mnt/spark_job"
  executor:
    cores: 1
    instances: 1
    memory: "512Mi"
    volumeMounts:
      - name: spark-pvc
        mountPath: "/mnt/spark_job"
