name: CI/CD for Airflow

on:
  workflow_run:
    workflows:
      - Flake8 Linting
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./airflow
        file: 
          - ./airflow/airflow_dockerfiles/Dockerfile-scheduler
          - ./airflow/airflow_dockerfiles/Dockerfile-webserver
          - ./airflow/airflow_dockerfiles/Dockerfile-worker
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/airflow:latest

    - name: Configure kubectl
      run: |
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f ./airflow/kubernetes/deployment.yaml
        kubectl apply -f ./airflow/kubernetes/service.yaml
