name: Build and Push Docker Image for KubernetesPodOperator

on:
  push:
    paths:
      - 'python_dockerfile/**'
  pull_request:
    paths:
      - 'python_dockerfile/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # 체크아웃 레포지토리
      - name: Checkout repository
        uses: actions/checkout@v3

      # 로그인 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 빌드 및 푸시 Docker 이미지 (PR일 경우)
      - name: Build Docker Image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./python_dockerfile/Dockerfile.k8spodimage
          push: true
          tags: |
            coffeeisnan/pod_image:latest
          build-args: | # ARG 값 전달
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 빌드 및 푸시 Docker 이미지 (push 이벤트일 경우)
      - name: Build and Push Docker Image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./python_dockerfile/Dockerfile.k8spodimage
          push: true
          tags: |
            coffeeisnan/python_pod_image:latest
          build-args: | # ARG 값 전달
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
