name: Lint and Format with Ruff and Black

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # PR 생성을 위한 권한

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Upgrade pip
      run: pip install --upgrade pip

    - name: Install Ruff and Black
      run: pip install ruff==0.8.5 black==24.10.0

    - name: Run Ruff (Lint and Fix)
      run: ruff check . --fix

    - name: Run Black (Log Diff and Apply Changes)
      run: |
        echo "Running Black to log potential changes..."
        black . --diff
        black .

    - name: Commit changes (if necessary)
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --cached --quiet || git commit -m "chore: Apply formatting with Ruff and Black"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: Apply formatting with Ruff and Black"
        branch: auto-format/${{ github.head_ref || github.run_id }}
        title: "chore: Apply formatting with Ruff and Black"
        body: |
          This PR applies automatic code formatting and lint fixes using Ruff and Black.
