name: Build and push dbt image

on:
  push:
    branches:
      - main
    paths:
      - dbt_dockerfiles/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      working-directory: dbt_dockerfiles
      run: docker build -f Dockerfile.dbt -t coffeeisnan/dbt_image:latest .

    - name: Push Docker image
      run: docker push coffeeisnan/dbt_image:latest
