name: Delete EKS Cluster

on:
  workflow_dispatch:

jobs:
  delete-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Delete EKS Cluster
      run: |
        aws eks delete-cluster --name ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
        while aws eks describe-cluster --name ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}; do
          echo "Waiting for cluster deletion..."
          sleep 30
        done