name: Flake8 Linting

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: check-code
        uses: actions/checkout@v3

      - name: python-setting
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 원하는 Python 버전

      - name: installing-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: flake8-linting
        run: flake8 .
