name: Build and Push Spark Job Docker Image

on:
  push:
    branches:
      - main
    paths:
      - spark/spark_job/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        working-directory: spark
        run: |
          docker build -f Dockerfile.sparkoperator -t coffeeisnan/spark-job:latest .

      - name: Push Docker image
        run: |
          docker push coffeeisnan/spark-job:latest
